image: registry.naspersclassifieds.com/shared-services/core-services/build-runtime

services:
  - docker:dind

before_script:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
  - rustup update
  - cargo install cargo-make
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
- build-base
- build
- tests

build-base-image:
  stage: build-base
  only:
    refs:
      - master

  script:
    - cargo make build_base_image

build:
  stage: build
  only:
    refs:
      - master
  script:
    - cargo make build_image

e2e:
  stage: tests
  script:
    - cargo make test
    - cargo make down