image: registry.naspersclassifieds.com/shared-services/core-services/build-runtime

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

stages:
- build-base
- build
- tests

build-base-image:
  stage: build-base
  script:
    - make build-base-image
  only:
    refs:
      - master

build:
  stage: build
  script:
    - make build-image
  only:
    refs:
      - master

e2e:
  stage: tests
  script:
    - make test