image: registry.naspersclassifieds.com/shared-services/core-services/build-runtime

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  - docker login -u "$ARTIFACTORY_USER" -p "$ARTIFACTORY_PASSWORD" docker.artifactory.olx.berlin

stages:
- build-base
- build
- tests
- deploy staging

build-base-image:
  stage: build-base
  variables:
    REVISION: ${CI_COMMIT_SHA}
  script:
    - make build-base-image
  only:
    changes:
      - Dockerfile.base
      - Makefile
    refs:
      - master

build:
  stage: build
  variables:
    REVISION: ${CI_COMMIT_SHA}
  script:
    - make build-image
  only:
    refs:
      - master

e2e:
  image: registry.naspersclassifieds.com/library/docker/build-images/deploy-dind:latest
  stage: tests
  script:
    - make test
    
.deploy:
  image: registry.naspersclassifieds.com/shared-services/core-services/deployment-util:latest
  before_script:
  - REVISION="${CI_COMMIT_SHA}"
  script:
  - /usr/bin/deploymentUtil --resource="${IMAGE_NAME}-v1" --tag="${REVISION}"
  only:
    refs:
    - master

deploy-staging:
  extends: .deploy
  stage: deploy staging
  environment:
    name: staging