version: '3'
services:
  s3:
    image: docker.artifactory.olx.berlin/naspersclassifieds/apollo-dev-minio:v1.0
    volumes:
      - /data
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=apollousr
      - MINIO_SECRET_KEY=apollopwd
    command: server /data
  rustbier:
    image: registry.naspersclassifieds.com/shared-services/core-services/rustbier/rustbier:${VERSION_TAG:-latest}
    volumes:
      - ./config:/config
    ports: 
      - 8080:8080
    environment: 
      - AWS_ACCESS_KEY_ID=apollousr
      - AWS_SECRET_ACCESS_KEY=apollopwd
      - RUN_MODE=compose
    depends_on: 
      - s3
volumes:
  s3-data:
    driver: local
