[config]
end_task = "down"

[env]
AWS_ACCESS_KEY_ID = "apollousr"
AWS_SECRET_ACCESS_KEY = "apollopwd"

[tasks.up]
script = [
    "docker-compose up -d"
]

[tasks.upload_test]
dependencies = ["up"]
script = [
    "docker-compose exec s3 mkdir /data/apollo || true",
    "docker cp tests/resources/watermark rustbier_s3_1:/data/apollo/watermark",
    "docker cp tests/resources/highres rustbier_s3_1:/data/apollo/highres",
    "docker cp tests/resources/img-test rustbier_s3_1:/data/apollo/img-test"
]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["upload_test"]

[tasks.down]
script = [
    "docker-compose down"
]

[tasks.build_base_image]
script = [
    "docker build -f base.Dockerfile -t registry.naspersclassifieds.com/shared-services/core-services/rustbier/base-rust-image .",
    "docker push registry.naspersclassifieds.com/shared-services/core-services/rustbier/base-rust-image"
]

[tasks.build_image]
script = [
    "docker build -t registry.naspersclassifieds.com/shared-services/core-services/rustbier/rustbier .",
    "docker push registry.naspersclassifieds.com/shared-services/core-services/rustbier/rustbier"
]